
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENT_FROM_EFFECT = 'INCREMENT_FROM_EFFECT';
export const DECREMENT_FROM_EFFECT = 'DECREMENT_FROM_EFFECT';

